### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources.extern

### ISSUE THREAD

**Issue by hermstadalex** [anntzer/pypi2pkgbuild#2] opened 2017-01-25 22:49 UTC
Hello, I am trying to try out this library, but I am running into some issues with my installation.

I am running on a docker image for arch, and I install your library by cloning the repository, and then running `pip install .`

After it is installed, I run `python pypi2pkgbuild.py django-braces` but I get this error:

`Traceback (most recent call last):
  File "pypi2pkgbuild.py", line 30, in <module>
    from pkg_resources.extern.packaging.version import parse as version_parse
ModuleNotFoundError: No module named 'pkg_resources.extern'`

Any ideas why this is happening? I have pip/setuptools installed. Also I am running python version 3.6, I am not sure if that is an issue.

**Comment by anntzer** [comment] 2017-01-25 23:25
Thanks for the report.

This is due to `setuptools` no longer vendoring `packaging` since two days ago (http://setuptools.readthedocs.io/en/latest/history.html#v34-0-0).  Now fixed, please check whether it works for you.

**Comment by hermstadalex** [comment] 2017-01-25 23:34
Thanks for the fast response. I'm now getting this error

`[root@b28b47c55c19 pypi2pkgbuild]# pypi2pkgbuild.py django-sentry
Traceback (most recent call last):
  File "/usr/sbin/pypi2pkgbuild.py", line 1169, in <module>
    sys.exit(main())
  File "/usr/sbin/pypi2pkgbuild.py", line 1149, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/sbin/pypi2pkgbuild.py", line 987, in create_package
    pkg = dispatch_package_builder(name, get_config(), options)
  File "/usr/sbin/pypi2pkgbuild.py", line 980, in get_config
    _run_shell("makepkg", cwd=tmpdir, stdout=PIPE, stderr=PIPE)
  File "/usr/sbin/pypi2pkgbuild.py", line 265, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'makepkg' returned non-zero exit status 1.`

**Comment by anntzer** [comment] 2017-01-25 23:37
Try running with `-v` (verbose) and paste the log?

**Comment by hermstadalex** [comment] 2017-01-25 23:56
As in this? `pypi2pkgbuild.py django-sentry -v`

That gives me

`DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile pkgfile >/dev/null
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmpwkdt82ko:
makepkg
Traceback (most recent call last):
  File "/usr/sbin/pypi2pkgbuild.py", line 1169, in <module>
    sys.exit(main())
  File "/usr/sbin/pypi2pkgbuild.py", line 1149, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/sbin/pypi2pkgbuild.py", line 987, in create_package
    pkg = dispatch_package_builder(name, get_config(), options)
  File "/usr/sbin/pypi2pkgbuild.py", line 980, in get_config
    _run_shell("makepkg", cwd=tmpdir, stdout=PIPE, stderr=PIPE)
  File "/usr/sbin/pypi2pkgbuild.py", line 265, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'makepkg' returned non-zero exit status 1.`

**Comment by anntzer** [comment] 2017-01-26 00:07
Try with the last version.  It will NOT fix the issue (which I cannot reproduce locally), but hopefully it'll print out more info about the error and we'll know how to go from there.

PS: You should use three backtracks for pasting multiline output.

**Comment by hermstadalex** [comment] 2017-01-26 00:31
Thanks for the tip!

Here's the output of the new version:

```[root@b28b47c55c19 pypi2pkgbuild]# pypi2pkgbuild.py -v django-braces
DEBUG:pypi2pkgbuild:Running subprocess:
pkgfile pkgfile >/dev/null
DEBUG:pypi2pkgbuild:Running subprocess from /tmp/tmp2tg2mamj:
makepkg
Traceback (most recent call last):
  File "/usr/sbin/pypi2pkgbuild.py", line 1169, in <module>
    sys.exit(main())
  File "/usr/sbin/pypi2pkgbuild.py", line 1149, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/sbin/pypi2pkgbuild.py", line 987, in create_package
    pkg = dispatch_package_builder(name, get_config(), options)
  File "/usr/sbin/pypi2pkgbuild.py", line 980, in get_config
    _run_shell("makepkg", cwd=tmpdir, stdout=PIPE, stderr=PIPE)
  File "/usr/sbin/pypi2pkgbuild.py", line 265, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'makepkg' returned non-zero exit status 1.```




Not sure if I'm missing any dependencies or anything. I have python-pip and pkgfile installed.

**Comment by anntzer** [comment] 2017-01-26 00:55
Try running the following shell script (basically what pypi2pkgbuild generates):
```
#!/bin/sh
mkdir -p /tmp/testpkg # replace by appropriate temporary folder
cd /tmp/testpkg
cat <<'EOF' >PKGBUILD
pkgver=0
pkgrel=0
arch=(any)
prepare() { printf "%s
" "$PACKAGER"; exit 0; }
EOF
makepkg
```

What does it say?

**Comment by hermstadalex** [comment] 2017-01-26 03:14
When I run that, I get

`==> ERROR: pkgname is not allowed to be empty.`

**Comment by hermstadalex** [comment] 2017-01-26 03:18
Also, this is the content of PKGBUILD after the script runs:

```
pkgver=0
pkgrel=0
arch=(any)
prepare() { printf "%s
" "$PACKAGER"; exit 0; }
```

**Comment by hermstadalex** [comment] 2017-01-26 04:53
I ran `python pypi2pkgbuild.py django-braces` again on a freshly configured arch image, and I'm also getting the same error now: 

```
==> ERROR: pkgname is not allowed to be empty.
Traceback (most recent call last):
  File "pypi2pkgbuild.py", line 1167, in <module>
    sys.exit(main())
  File "pypi2pkgbuild.py", line 1147, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "pypi2pkgbuild.py", line 985, in create_package
    pkg = dispatch_package_builder(name, get_config(), options)
  File "pypi2pkgbuild.py", line 979, in get_config
    maintainer = _run_shell("makepkg", cwd=tmpdir, stdout=PIPE).stdout
  File "pypi2pkgbuild.py", line 265, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'makepkg' returned non-zero exit status 1.
```

Perhaps my usage is wrong? The argument I specify, `django-braces` is a python package in the pip package manager.

**Comment by anntzer** [comment] 2017-01-26 05:03
It looks like you have a slightly different version of makepkg that I do (mine accepts empty pkgnames -- this is just a temporary PKGBUILD use to retrieve some info from makepkg.conf (which can be in various places) without having to parse it).  What did you install Arch from?

In any case, I just pushed a fix that should work even in your case.  Please give it a try.  For me django-braces appears correctly packaged (your usage is correct).

**Comment by hermstadalex** [comment] 2017-01-26 05:32
Looks like that gets me a lot further in the packaging. This is now my traceback:

```
INFO:pypi2pkgbuild:Packaging python-django-braces 1.10.0.
Collecting django-braces
  Using cached django-braces-1.10.0.tar.gz
  Saved /tmp/tmppbsp82co/django-braces-1.10.0.tar.gz
Successfully downloaded django-braces
Initialized empty Git repository in /home/alex/pypi2pkgbuild/python-django-braces/.git/
Collecting django-braces
  Using cached django_braces-1.10.0-py2.py3-none-any.whl
  Saved /tmp/tmpwnp6cz9a/django_braces-1.10.0-py2.py3-none-any.whl
Successfully downloaded django-braces
==> Making package: python-django-braces 1.10.0-00 (Thu Jan 26 05:26:16 UTC 2017)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found django_braces-1.10.0-py2.py3-none-any.whl
  -> Found LICENSE
==> Validating source files with md5sums...
    django_braces-1.10.0-py2.py3-none-any.whl ... Passed
    LICENSE ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting build()...
==> Starting check()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "python-django-braces"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-django-braces 1.10.0-00 (Thu Jan 26 05:26:18 UTC 2017)
Traceback (most recent call last):
  File "pypi2pkgbuild.py", line 1176, in <module>
    sys.exit(main())
  File "pypi2pkgbuild.py", line 1156, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "pypi2pkgbuild.py", line 997, in create_package
    pkg.write_to(options)
  File "pypi2pkgbuild.py", line 639, in write_to
    namcap = (_run_shell(["namcap", fullpath.name], cwd=cwd, stdout=PIPE)
  File "pypi2pkgbuild.py", line 265, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'namcap'
```

It seems like it actually finishes packaging it. I have a directory called python-django-braces that has this in it: `LICENSE  PKGBUILD  PKGBUILD_EXTRAS  django_braces-1.10.0-py2.py3-none-any.whl  pkg  python-django-braces-1.10.0-00-any.pkg.tar.xz  src`

There is just that traceback at the very end that I'm not sure of.

P.S: I'm running arch with docker, using the base/archlinux image.

**Comment by anntzer** [comment] 2017-01-26 06:01
Indeed, I had missed that there is a dependency on [namcap](https://wiki.archlinux.org/index.php/namcap).  Please first try the new version before installing namcap, it should give you a clearer error message (please confirm).  Then install namcap and try again.

It's a bit strange that makepkg is different in the docker image, but I guess I can live with that...

**Comment by hermstadalex** [comment] 2017-01-26 06:14
Yep, here's the error it gives:

```
usage: pypi2pkgbuild.py [-h] [-v] [-o] [-u] [-i NAME,...] [-b BASE_PATH] [-f]
                        [-p] [-r PKGREL] [-g MAKEDEPENDS,...]
                        [-s PYPI_NAME,...] [-t PKGTYPES] [-d]
                        [-m MAKEPKG_OPTS]
                        [name [name ...]]
pypi2pkgbuild.py: error: Missing dependency: namcap
```

Though now after installing it, I'm getting a new set of errors which I'm currently looking into debugging. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/namcap.py", line 32, in <module>
    import Namcap.depends
  File "/usr/lib/python3.6/site-packages/Namcap/__init__.py", line 20, in <module>
    from . import util, rules
  File "/usr/lib/python3.6/site-packages/Namcap/rules/__init__.py", line 24, in <module>
    from . import (
  File "/usr/lib/python3.6/site-packages/Namcap/rules/kdeprograms.py", line 22, in <module>
    import Namcap.depends
  File "/usr/lib/python3.6/site-packages/Namcap/depends.py", line 30, in <module>
    from Namcap import package
  File "/usr/lib/python3.6/site-packages/Namcap/package.py", line 29, in <module>
    import pyalpm
ImportError: /usr/lib/libcurl.so.4: undefined symbol: SSLv3_client_method
Traceback (most recent call last):
  File "pypi2pkgbuild.py", line 1166, in <module>
    sys.exit(main())
  File "pypi2pkgbuild.py", line 1146, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "pypi2pkgbuild.py", line 987, in create_package
    pkg.write_to(options)
  File "pypi2pkgbuild.py", line 629, in write_to
    namcap = (_run_shell(["namcap", fullpath.name], cwd=cwd, stdout=PIPE)
  File "pypi2pkgbuild.py", line 257, in _run_shell
    return subprocess.run(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['namcap', 'python-django-braces-1.10.0-00-any.pkg.tar.xz']' returned non-zero exit status 1.
```

**Comment by anntzer** [comment] 2017-01-26 06:19
That looks like some ABI mistmatch error.  Does `python -c 'import pyalpm'` or just `namcap` raise the same error?

As a side note I've squashed some commits among the recent fixes as they were becoming quite small.  If you keep reusing the same repo you'll need to do something like `git fetch && git reset --hard origin/master` next time to update.  (Haven't changed anything for now regarding your issue.)

**Comment by hermstadalex** [comment] 2017-01-26 06:21
It seems I've fixed it with a pacman upgrade command. Looks like I've got it working and it's packaging django-braces successfully. 

Thanks for all your help, and a big thanks for writing this library!

**Comment by anntzer** [comment] 2017-01-26 06:26
No worries.  I don't think this library is very widely used (yet?), so feedback (including about general usability) is very welcome.

**Closed as completed** 2017-01-26 06:26 UTC

**Comment by hermstadalex** [comment] 2017-01-26 06:43
One last question I have, unrelated to this (not sure if I should open up a new issue for it or what):

Part of a task I need to do is to is create an arch package out of a .whl file, which I have a copy of but is not on PyPi/pip package repository yet. I saw that this library had support for .whl formats, but  can it solve the problem that I have? It seems that this library is for packaging things that are already in the PyPi repository.

If not, do you have any suggestions of where how to solve this?

**Comment by anntzer** [comment] 2017-01-26 07:26
Say your wheel ($pkgname-$pkgver-$etc.whl) is in the local directory, then do
```
PIP_EXTRA_INDEX_URL=. pypi2pkgbuild.py $pkgname # not the full filename!
```
This basically makes pip believe that the local dir is a pypi repository.

**Comment by anntzer** [comment] 2017-01-26 17:17
I added an entry at the bottom of the usage notes (https://github.com/anntzer/pypi2pkgbuild#usage-notes) on this topic.  How does it look to you?

**Comment by hermstadalex** [comment] 2017-01-26 17:57
I'm not sure that I fully understand. In my case, my whl file is `klorn_static-0.1.1rc1-py2.py3-none-any.whl`

So I am assuming the package name should be simply `klorn_static`

As per the usage notes, should I be doing something like:

```
$ PIP_EXTRA_INDEX_URL=whl_folder \
      pypi2pkgbuild.py klorn_static  # (package name, not wheel name)
```

Where `whl_folder` contains my wheel file? If so, I'm getting the error that the package is not found:

`ERROR:pypi2pkgbuild:Package klorn_static  not found.`

**Comment by anntzer** [comment] 2017-01-26 18:43
1. Does `pip install klorn_static-0.1.1rc1-py2.py3-none-any.whl` work?
2. Does `pip install --extra-index-url=whl_folder klorn_static` work?

(You probably need to uninstall between each attempt.)

**Comment by hermstadalex** [comment] 2017-01-26 18:54
`pip install klorn_static-0.1.1rc1-py2.py3-none-any.whl` works:

```
[alex@84d80e05ee1b pypi2pkgbuild]$ sudo pip install klorn_static-0.1.1rc1-py2.py3-none-any.whl 
Processing ./klorn_static-0.1.1rc1-py2.py3-none-any.whl
Installing collected packages: klorn-static
Successfully installed klorn-static-0.1.1rc1
```

`pip install --extra-index-url=whl_folder klorn_static` gives me this:

```
[alex@84d80e05ee1b pypi2pkgbuild]$ sudo pip install --extra-index-url=whl_folder klorn_static
Collecting klorn_static
  Url 'whl_folder/klorn-static/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Could not find a version that satisfies the requirement klorn_static (from versions: )
No matching distribution found for klorn_static
```

It appears that it ignores the specified folder as a url?

**Comment by anntzer** [comment] 2017-01-26 19:26
Sorry, I was incorrect.  The correct flag for a local folder is `--find-links=<blah>` / `PIP_FIND_LINKS=<blah>`.  Unfortunately the later is not supported right now by pypi2pkgbuild.py; it should be possible to add that but that'll need a bit of work so it won't happen right now.

**Comment by hermstadalex** [comment] 2017-01-26 22:50
Ah I see. So for now, the only way to use pypi2pkgbuild is if the package is on the official pip repository?

**Comment by anntzer** [comment] 2017-01-26 23:30
You can also install from a git repository that contains the source (i.e., including a `setup.py`) via `pypi2pkgbuild.py git+https://<blah>` or `pypi2pkgbuild.py git+file://<blah>`.

**Comment by hermstadalex** [comment] 2017-01-27 00:33
Thanks for the tip. So I'm trying pypi2pkgbuild with another of my packages, and I'm getting an error `ERROR:pypi2pkgbuild:No suitable release found.` 

Here's the link to the PyPi page it's on: [Kolibri](https://pypi.python.org/pypi/kolibri/)

Any ideas on why this is happening or what to do about it? Looks like it's in a .whl format as well as .tar.gz on PyPi.

**Comment by anntzer** [comment] 2017-01-27 00:48
Looks like the package only has prereleases, which are excluded by default.  `pypi2pkgbuild.py --pre kolibri` does pull the prerelease.  In fact I strongly believe that `pip` itself should not install prereleases by default, even though it does (see https://github.com/pypa/pip/issues/1545).

**Comment by anntzer** [comment] 2017-01-27 00:51
I added a clearer error message (suggesting to use --pre) when such a case happens.

**Comment by hermstadalex** [comment] 2017-01-27 01:20
Gotcha, thanks for the clarification.

**Comment by anntzer** [comment] 2017-01-27 09:41
Actually I have been able to hack something quickly for local wheels.  See the last entry in the Usage Notes.  (It may have some minor issues in which case we'll need to go through a few iterations, please let me know.)

Note that there are *three* slashes and an *absolute* path is required.  Additionally, if a local wheel depends on other local wheels, they need to be built one at a time in topological order (even if `-d` is passed).

**Comment by anntzer** [comment] 2017-01-29 08:39
@hermstadalex did you have a chance to give it a try?

**Comment by hermstadalex** [comment] 2017-01-29 17:27
Whoops, forgot to send the message. I tried it, and it appears to be
working as intended. It might help though, in the usage notes under this
topic to mention that the dependencies for wheels have to be built in the
correct order.

**Comment by anntzer** [comment] 2017-01-29 17:45
Done.  Unfortunately I don't think it'll be easy to lift that restriction -- I added a sentence explaining why, too.  (I guess an alternative would be to default to normalize using pypi normalization (i.e. "-" replacing runs of non-alnum characters.  This seems used by a majority of arch packages.
```
pacman -Slq | grep '^python-' | cut -d- -f 2- | grep -v '^\([[:alnum:]]\)*$' | grep '-' 
pacman -Slq | grep '^python-' | cut -d- -f 2- | grep -v '^\([[:alnum:]]\)*$' | grep '_' 
pacman -Slq | grep '^python-' | cut -d- -f 2- | grep -v '^\([[:alnum:]]\)*$' | grep '\.' 
```
)

**Comment by anntzer** [comment] 2017-01-29 22:40
Actually even that issue (packages built out of order) should be fixed now.  Pass `-d` (skip building dependencies) for that.
